### ISSUE TITLE
Reading via pyHive broken?

### ISSUE THREAD

**Issue by randerzander** [dask-contrib/dask-sql#233]
I'm attempting to read from a HiveServer2 instance w/ dask-sql, but running into a error. It looks like a failure to read_csv?

```
from dask_sql import Context
from pyhive.hive import connect

cursor = connect("localhost", 10000).cursor()

cursor.execute("""
CREATE EXTERNAL TABLE test (
  id STRING,
    val INT
    )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
location '/data/data/test_csv/'
""")

# confirm pyhive/hiveserver2 communicating
cursor.execute("select * from test")
print(cursor.fetchall())
# [('0', 0), ('1', 1), ('2', 2)]

# attempt to read with dask-sql
c = Context()
c.create_table("ds_test", cursor, hive_table_name="test")
```

Trace:
```
Traceback (most recent call last):
  File "hive_test.py", line 23, in <module>
    c.create_table("ds_test", cursor, hive_table_name="test")
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask_sql/context.py", line 199, in create_table
    dc = InputUtil.to_dc(
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask_sql/input_utils/convert.py", line 59, in to_dc
    table = filled_get_dask_dataframe(input_item)
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask_sql/input_utils/convert.py", line 52, in <lambda>
    filled_get_dask_dataframe = lambda *args: cls._get_dask_dataframe(
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask_sql/input_utils/convert.py", line 81, in _get_dask_dataframe
    return plugin.to_dc(
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask_sql/input_utils/hive.py", line 184, in to_dc
    df = wrapped_read_function(location, column_information, **kwargs)
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask_sql/input_utils/hive.py", line 130, in wrapped_read_function
    df = read_function(location, **kwargs)
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask/dataframe/io/csv.py", line 725, in read
    return read_pandas(
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask/dataframe/io/csv.py", line 522, in read_pandas
    compression = infer_compression(paths[0])
IndexError: list index out of range
```

When I create a Parquet version of the same data, I get a different error:
```
>>> cursor.execute("create table testpq stored as parquet as select * from test")
>>> cursor.execute("select * from testpq")
>>> cursor.fetchall()
[('0', 0), ('1', 1), ('2', 2)]

>>> c.create_table('ds_test2', cursor, hive_table_name='testpq')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'c' is not defined
>>> c = Context()
>>> c.create_table('ds_test2', cursor, hive_table_name='testpq')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask_sql/context.py", line 199, in create_table
    dc = InputUtil.to_dc(
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask_sql/input_utils/convert.py", line 59, in to_dc
    table = filled_get_dask_dataframe(input_item)
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask_sql/input_utils/convert.py", line 52, in <lambda>
    filled_get_dask_dataframe = lambda *args: cls._get_dask_dataframe(
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask_sql/input_utils/convert.py", line 81, in _get_dask_dataframe
    return plugin.to_dc(
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask_sql/input_utils/hive.py", line 184, in to_dc
    df = wrapped_read_function(location, column_information, **kwargs)
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask_sql/input_utils/hive.py", line 130, in wrapped_read_function
    df = read_function(location, **kwargs)
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 362, in read_parquet
    meta, index, columns = set_index_columns(
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 1180, in set_index_columns
    raise ValueError(
ValueError: The following columns were not found in the dataset {'id', 'val'}
The following columns were found Index([], dtype='object')
```

What assumptions does Dask-SQL make about the path it will actually use to read data? In my case, HS2 is running in a separate container, so I suspect the Python process running dask-sql cannot see the underlying data files. It might be helpful for dask-sql to print some information about the attempted read path.

**Comment by nils-braun** [comment]
You are absolutely correct with your assumption: in the way you created the table, dask-sql will only get the location from Hive and will then try to read the data "by itself" from the specified location.

I like the idea of having more information on the error message. Maybe we can check if there is at least a single file before trying the actual read. If you turn on debug logging, I think there ja actually some information (but this, on the other hand, should not be the default way, so we should improve the error message).

Side-Story: to solve the problem (assuming it was not just a toy example), you probably need to read not only the location but the full  data via Hive. You can do so with the "normal" read_sql method of dask. The resulting dataframe can then be registered at Dask-sql. The reason we are not doing this by default but only getting the location and reading in ourselves is a possible speed improvement.
