### ISSUE TITLE
[DOC] API docs not rendering

### ISSUE THREAD

**Issue by ayushdg** [dask-contrib/dask-sql#401]
## Report incorrect documentation

**Location of incorrect documentation**
The api documentations [page](https://dask-sql.readthedocs.io/en/latest/pages/api.html) returns a blank page on the docs site.

Might be similar to #215 

---

**Comment by charlesbluca** [comment]
Attempting to build the docs, it looks like we fail when trying to load in a non-existent function:

```
Running Sphinx v4.4.0
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: 0 added, 15 changed, 0 removed
reading sources... [100%] sql/select                                                                                                                                                                                                                                                                                  
WARNING: autodoc: failed to import function 'fsql' from module 'dask_sql.integrations.fugue'; the following exception was raised:
Traceback (most recent call last):
  File "/datasets/charlesb/miniconda3/envs/dask-sql-docs/lib/python3.9/site-packages/sphinx/util/inspect.py", line 448, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'dask_sql.integrations.fugue' has no attribute 'fsql'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/datasets/charlesb/miniconda3/envs/dask-sql-docs/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/datasets/charlesb/miniconda3/envs/dask-sql-docs/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 332, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/datasets/charlesb/miniconda3/envs/dask-sql-docs/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2828, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/datasets/charlesb/miniconda3/envs/dask-sql-docs/lib/python3.9/site-packages/sphinx/util/inspect.py", line 464, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: fsql
```

Looks like `dask_sql.integrations.fugue.fsql` might have been relocated to `fsql_dask`? If that's the only issue then it should be a hypothetically easy fix, although I'm interested in why this wouldn't have cause the RTD builds to fail outright.

Think this is a good motivator to add RTD builds to PRs, which should give us a better idea of when code changes will break the docs.

**Comment by charlesbluca** [comment]
It looks like this breakage in particular is because of https://github.com/dask-contrib/dask-sql/pull/396, as `python setup.py install` no longer builds the Java extensions, which are needed for the API docs.

I will see if we can customize the build script for dask-sql, otherwise we may need to make a custom `build_ext` step as suggested in https://github.com/dask-contrib/dask-sql/issues/400 so that the Java / Python builds are consolidated
